# Use ubuntu trusty (14.04) with sudo privileges.
# sudo is required to use docker service in travis
sudo: required
language: generic
notifications:
  email: false
env:
  global:
  - CI_SOURCE_PATH=$(pwd)
  - secure: YwkBy2Y4P3VaISkWwYgDdelDSXziNBbglbZzCdILDpQopsTotfZx2/HxLTeJa5lAoa9C06Nz0dflwGFy3bvgZe3OFs89pzea2hNNAHvrbDjdrFq2MOZjaga4sxmCrDWf5M6VJJxfoNS/qNaL0zB2Q8h9gHMX7ObflSP9Tpfa8H0K2SITnR8l4K3XdGNQo1V1TPV3FMyZWA3dqY3pvI1h2hxhH2DQki7Kbi4kdVBHZiy8JhrOyCYGciiK27w2KcvNLIuWeR6KUMjgZqtX1LzSRbjVqr7LA+K5oYh+p87tzyS7xAoGXtyy9vVNPdS+ENT6OFFrlHWOJHr1aqFQUhaDR5Q8RDPa0XoZRR3iKJAXBmJIz9pl4zCS4BWy7cHHrkpn0IndkuXNDW47aajmn/v/SIHwWQO1qDhyfAe14V01zTT6TrjVIQ0wUlUtoVV75IKKFqYYTaYgdvVge7/B96F3m/rxdRz93bNUsi+kWYrHffOQPwM2fDBmL/m5kpKseLvN9+j8dz/wV/EpkpZerHj1xCB1cMb+UD4T20br0XoxCioFAWeO6zG9P1cdcQqESl++bORhV/5NHLO9NyVre93RRv09N0XLWengAkn+3342rcy/x/uOf0K3owUGBwuhOmcGwxFRNI8VNO2NV+WxUutISDnAgIBkWDC4Pf0XLKDmLeI=
  - secure: Jcd4jwvE+nha4WIlhf964jgm1Zp2tzE1zPu/o1fCI853zhvd2xRMh1F4ZwGmS+DjibAbo2dXPjEPBiLW3RQj6yXDrZ+0rfIRBDWdkKk7y08tZkAJ68ITRm+0Ld1cUuN5LVWGsiVLAMknRX2yZoI1IaXsZAkgoYvGrzVKrXc/sQb9oJuJAr8hnSc7Cpwlog6onJciJwaURHfKpUBQLW3xW6O7tjiRJq3DTrQw0yzKikT082olrPziRUcJVQl8POVcYQG6YKAJPuEbh7L8oWEvU/mScb1Zwsa6gIVduSqg1y+x39I/i5hLH+a9Lc/pVTP0RQXAzYILqyPFrlgA7N49sdSqE99HjTQOduryi3V6x7LTQmjbhiIDN5CvgcxbklmgfrMWIK9DYg8LxlaLcxpWf1Zmq62BJoAvPoAV63fJGm5ONnQ25wJwoBbjXJpoCtQ9qee08m/vqlwXs0nGny1gxvtNQ5fOFswUPveb63tOltQlMNr98+1QrCHAAy+4/RPO5KFKHN7RZMSx0tpIdGyK5UjTxMK28/KAxmTcoEckMBuGfRLBmQmDHFWfOgxahHDCdWi5vh6h2Sys/k7yi5Ri+gCWwQ19SJTGR5wmQXAhIm+PLXW0xu7HZMPzNSolO9mWaXJitVhtKQyKrlEx7V6pofTyamzCauUPM/kbaJ0ccKk=
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull leia/ontosem:1.0.0
  - docker pull leia/agents:0.5.0

install:
  - docker --version  # document the version travis is using
  - docker-compose -f $CI_SOURCE_PATH/docker-compose.yml up -d # -d stands for detached version that runs containers on the background
  - docker ps -a

script:
  - "curl -s -H 'Content-type: application/json' -X POST -d '[[\"u\", \"We will build a chair.\"], [\"a\", \"get-screwdriver\"]]' 0.0.0.0:5002/learn"

after_success:
  - echo "Success!" # put your normal testing scripts here
  - docker-compose down
